#!/usr/bin/env bash
# Initialize db https://hub.docker.com/_/postgres#initialization-scripts
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER example_user with replication password 'secret';
    GRANT SET ON PARAMETER session_replication_role TO example_user;
    
	CREATE DATABASE example_db with owner example_user;
	CREATE DATABASE example_db1 with owner example_user;
    CREATE DATABASE example_db2 with owner example_user;

    -- create client table for sync1
    \c example_db
    set role example_user;
    create table client(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name character varying);
    create table product(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name character varying);
    
    \c example_db1
    set role example_user;
    create table client(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name character varying);
    create table client1(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name character varying);
    create table product(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name character varying);    
    
    \c example_db2
    set role example_user;
    create table client(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name character varying);
    create table product(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name character varying);    
    create table product2(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name character varying);    
    
EOSQL
